// Fix: Populated the file with constant data used across the application.
import type { Language, LanguageOption, User, Course, PracticeProblem, Contest, PastContest, LeaderboardUser, ContestProblem, RecentActivityItem, CourseDetails, Challenge, Snippet } from './types';

export const LANGUAGES: LanguageOption[] = [
  { id: 'c', name: 'C' },
  { id: 'cpp', name: 'C++' },
  { id: 'java', name: 'Java' },
  { id: 'javascript', name: 'JavaScript' },
  { id: 'python', name: 'Python' },
];

export const DEFAULT_CODE: Record<Language, string> = {
  c: `#include <stdio.h>

int main() {
    printf("Hello, World!\\n");
    return 0;
}`,
  cpp: `#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}`,
  java: `public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}`,
  javascript: `console.log("Hello, World!");`,
  python: `print("Hello, World!")`,
};

export const CODE_SNIPPETS: Record<Language, Snippet[]> = {
  c: [
    { title: 'For Loop', description: 'A standard for loop.', code: 'for (int i = 0; i < 10; i++) {\n    // code here\n}' },
    { title: 'While Loop', description: 'A standard while loop.', code: 'while (condition) {\n    // code here\n}' },
    { title: 'If-Else', description: 'A conditional statement.', code: 'if (condition) {\n    // code here\n} else {\n    // code here\n}' },
    { title: 'Function', description: 'A basic function definition.', code: 'void functionName() {\n    // code here\n}' },
    { title: 'Read Input (scanf)', description: 'Read integer from stdin.', code: 'int num;\nscanf("%d", &num);' },
  ],
  cpp: [
    { title: 'For Loop', description: 'A standard for loop.', code: 'for (int i = 0; i < 10; ++i) {\n    // code here\n}' },
    { title: 'While Loop', description: 'A standard while loop.', code: 'while (condition) {\n    // code here\n}' },
    { title: 'If-Else', description: 'A conditional statement.', code: 'if (condition) {\n    // code here\n} else {\n    // code here\n}' },
    { title: 'Function', description: 'A basic function definition.', code: 'void functionName() {\n    // code here\n}' },
    { title: 'Class', description: 'A basic class definition.', code: 'class MyClass {\npublic:\n    MyClass() {}\n    ~MyClass() {}\n};' },
    { title: 'Read Input (cin)', description: 'Read integer from stdin.', code: 'int num;\nstd::cin >> num;' },
  ],
  java: [
    { title: 'For Loop', description: 'A standard for loop.', code: 'for (int i = 0; i < 10; i++) {\n    // code here\n}' },
    { title: 'While Loop', description: 'A standard while loop.', code: 'while (condition) {\n    // code here\n}' },
    { title: 'If-Else', description: 'A conditional statement.', code: 'if (condition) {\n    // code here\n} else {\n    // code here\n}' },
    { title: 'Method', description: 'A basic method definition.', code: 'public void methodName() {\n    // code here\n}' },
    { title: 'Class', description: 'A basic class definition.', code: 'class MyClass {\n    public MyClass() {\n        \n    }\n}' },
    { title: 'Read Input (Scanner)', description: 'Read integer from stdin.', code: 'import java.util.Scanner;\n\nScanner scanner = new Scanner(System.in);\nint num = scanner.nextInt();' },
  ],
  javascript: [
    { title: 'For Loop', description: 'A standard for loop.', code: 'for (let i = 0; i < 10; i++) {\n    // code here\n}' },
    { title: 'While Loop', description: 'A standard while loop.', code: 'while (condition) {\n    // code here\n}' },
    { title: 'If-Else', description: 'A conditional statement.', code: 'if (condition) {\n    // code here\n} else {\n    // code here\n}' },
    { title: 'Function', description: 'A basic function definition.', code: 'function functionName() {\n    // code here\n}' },
    { title: 'Arrow Function', description: 'An ES6 arrow function.', code: 'const functionName = () => {\n    // code here\n};' },
    { title: 'Class', description: 'An ES6 class definition.', code: 'class MyClass {\n    constructor() {\n        \n    }\n}' },
  ],
  python: [
    { title: 'For Loop', description: 'A standard for loop.', code: 'for i in range(10):\n    # code here\n    pass' },
    { title: 'While Loop', description: 'A standard while loop.', code: 'while condition:\n    # code here\n    pass' },
    { title: 'If-Else', description: 'A conditional statement.', code: 'if condition:\n    # code here\nelse:\n    # code here\n    pass' },
    { title: 'Function', description: 'A basic function definition.', code: 'def function_name():\n    # code here\n    pass' },
    { title: 'Class', description: 'A basic class definition.', code: 'class MyClass:\n    def __init__(self):\n        pass' },
    { title: 'Read Input', description: 'Read a line from stdin.', code: 'data = input()' },
  ],
};

export const LANGUAGE_KEYWORDS: Record<Language, string[]> = {
  c: [
    'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
    'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if',
    'int', 'long', 'register', 'return', 'short', 'signed', 'sizeof', 'static',
    'struct', 'switch', 'typedef', 'union', 'unsigned', 'void', 'volatile', 'while',
    '#include', '#define', '#ifdef', '#ifndef', '#endif', '#if', '#else'
  ],
  cpp: [
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor', 'bool', 'break', 'case',
    'catch', 'char', 'char8_t', 'char16_t', 'char32_t', 'class', 'compl',
    'concept', 'const', 'consteval', 'constexpr', 'constinit', 'const_cast',
    'continue', 'co_await', 'co_return', 'co_yield', 'decltype', 'default',
    'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum', 'explicit',
    'export', 'extern', 'false', 'float', 'for', 'friend', 'goto', 'if',
    'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept', 'not',
    'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private', 'protected',
    'public', 'register', 'reinterpret_cast', 'requires', 'return',
    'short', 'signed', 'sizeof', 'static', 'static_assert', 'static_cast',
    'struct', 'switch', 'template', 'this', 'thread_local',
    'throw', 'true', 'try', 'typedef', 'typeid', 'typename', 'union',
    'unsigned', 'using', 'virtual', 'void', 'volatile', 'wchar_t', 'while',
    'xor', 'xor_eq', '#include', '#define'
  ],
  java: [
    'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char',
    'class', 'const', 'continue', 'default', 'do', 'double', 'else', 'enum',
    'extends', 'final', 'finally', 'float', 'for', 'goto', 'if', 'implements',
    'import', 'instanceof', 'int', 'interface', 'long', 'native', 'new',
    'package', 'private', 'protected', 'public', 'return', 'short', 'static',
    'strictfp', 'super', 'switch', 'synchronized', 'this', 'throw', 'throws',
    'transient', 'try', 'void', 'volatile', 'while', 'true', 'false', 'null'
  ],
  javascript: [
    'abstract', 'arguments', 'await', 'boolean', 'break', 'byte', 'case',
    'catch', 'char', 'class', 'const', 'continue', 'debugger', 'default',
    'delete', 'do', 'double', 'else', 'enum', 'eval', 'export', 'extends',
    'false', 'final', 'finally', 'float', 'for', 'function', 'goto', 'if',
    'implements', 'import', 'in', 'instanceof', 'int', 'interface', 'let',
    'long', 'native', 'new', 'null', 'package', 'private', 'protected',
    'public', 'return', 'short', 'static', 'super', 'switch', 'synchronized',
    'this', 'throw', 'throws', 'transient', 'true', 'try', 'typeof', 'var',
    'void', 'volatile', 'while', 'with', 'yield', 'async', 'of'
  ],
  python: [
    'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
    'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
    'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda',
    'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while',
    'with', 'yield'
  ]
};

export const LANGUAGE_FUNCTIONS: Record<Language, string[]> = {
  c: [
    'printf', 'scanf', 'malloc', 'free', 'fopen', 'fclose', 'strcpy', 'strlen', 'sizeof'
  ],
  cpp: [
    'std::cout', 'std::cin', 'std::endl', 'std::vector', 'std::string', 'std::sort', 
    'std::max', 'std::min', 'push_back', 'pop_back', 'size', 'begin', 'end'
  ],
  java: [
    'System.out.println', 'Math.max', 'Math.min', 'String.length', 'ArrayList.add', 
    'ArrayList.get', 'HashMap.put', 'HashMap.get', 'Integer.parseInt'
  ],
  javascript: [
    'console.log', 'Math.max', 'Math.min', 'Array.prototype.push', 'Array.prototype.pop', 
    'Array.prototype.map', 'Array.prototype.filter', 'String.prototype.length', 
    'JSON.parse', 'JSON.stringify', 'document.getElementById'
  ],
  python: [
    'print', 'input', 'len', 'range', 'str', 'int', 'float', 'list.append', 
    'list.pop', 'dict.get', 'sorted', 'max', 'min'
  ]
};


export const INITIAL_USER: User = {
  name: 'Himanshu',
  username: 'himanshu',
  avatarUrl: 'https://i.pravatar.cc/150?u=himanshu_profile',
  email: 'himanshun102@gmail.com',
  college: 'SAGE University',
  course: 'Computer Science',
  stats: [
    { label: 'Rank', value: 1234 },
    { label: 'Problems', value: 150 },
    { label: 'Points', value: 3200 },
  ],
};

export const COURSES: Course[] = [
    { title: 'Object Oriented Programming in C++', category: 'Programming', lessons: 30, hours: 10, level: 'Beginner', color: 'bg-blue-500' },
    { title: 'Data Structures in Java', category: 'Algorithms', lessons: 32, hours: 18, level: 'Intermediate', color: 'bg-red-500' },
    { title: 'Data Structures Using C', category: 'Algorithms', lessons: 45, hours: 25, level: 'Intermediate', color: 'bg-green-500' },
];

const C_PLUS_PLUS_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-white"><path d="M12 12H16"/><path d="M14 10V14"/><path d="M18 12h4"/><path d="M20 10v4"/><path d="M8 16H4.5a2.5 2.5 0 1 1 0-5H8"/><path d="M5 12v0"/><path d="M20 18a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2z"/></svg>`;
const PYTHON_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-white"><path d="M10.2 2.5c-.2.3-.4.6-.5.9-.3 1.2.3 2.5 1.5 2.8 1.2.3 2.5-.3 2.8-1.5.3-1.2-.3-2.5-1.5-2.8-.3-.1-.7-.1-1 0l-1.3 1.6V15c0 3.3 2.7 6 6 6h2"/><path d="M13.8 21.5c.2-.3.4-.6.5-.9.3-1.2-.3-2.5-1.5-2.8-1.2-.3-2.5.3-2.8 1.5-.3 1.2.3 2.5 1.5 2.8.3.1.7.1 1 0l1.3-1.6V9c0-3.3-2.7-6-6-6H7"/></svg>`;
const ALGORITHMS_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-white"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"/><path d="M12 12v9"/><path d="m8 17 4 4 4-4"/></svg>`;

export const PRACTICE_PROBLEMS: PracticeProblem[] = [
  { name: 'C++', description: 'Master C++ from basics to advanced topics like OOP and memory management.', problems: 120, level: 'All Levels', icon: C_PLUS_PLUS_ICON, color: 'bg-blue-600' },
  { name: 'Python', description: 'Solve problems with Python, focusing on its clean syntax and powerful libraries.', problems: 150, level: 'All Levels', icon: PYTHON_ICON, color: 'bg-yellow-500' },
];

export const SUBJECT_PROBLEMS: PracticeProblem[] = [
  { name: 'Algorithms', description: 'Sharpen your problem-solving skills with a wide range of algorithmic challenges.', problems: 250, level: 'Intermediate', icon: ALGORITHMS_ICON, color: 'bg-green-600' },
];

export const CONTESTS: Contest[] = [
  { title: 'Weekly Contest #345', startTime: 'Starts in 2d 4h 30m', duration: '90 mins', participants: 1250 },
  { title: 'Biweekly Contest #112', startTime: 'Starts in 9d 4h 30m', duration: '120 mins', participants: 980 },
];

export const PAST_CONTESTS: PastContest[] = [
  { name: 'Weekly Contest #344', date: 'July 15, 2024' },
  { name: 'Weekly Contest #343', date: 'July 8, 2024' },
];

export const LEADERBOARD_USERS: LeaderboardUser[] = [
  { rank: 1, name: 'CodeMaster', score: 10500 },
  { rank: 2, name: 'AlgoQueen', score: 10250 },
  { rank: 3, name: 'BytePuzzler', score: 9800 },
];

export const CONTEST_PROBLEMS: ContestProblem[] = [
  { id: 'A', title: 'Two Sum Variant', difficulty: 'Easy', points: 300 },
  { id: 'B', title: 'Max Subarray Sum', difficulty: 'Medium', points: 500 },
  { id: 'C', title: 'Binary Tree Paths', difficulty: 'Medium', points: 600 },
  { id: 'D', title: 'Word Ladder', difficulty: 'Hard', points: 1000 },
];

export const RECENT_ACTIVITIES: RecentActivityItem[] = [
  { id: 1, title: 'Two Sum Variant', status: 'Accepted', timestamp: '5 minutes ago' },
  { id: 2, title: 'Max Subarray Sum', status: 'Wrong Answer', timestamp: '1 hour ago' },
  { id: 3, title: 'Binary Tree Paths', status: 'Time Limit Exceeded', timestamp: '3 hours ago' },
];

export const COURSE_DETAILS: Record<string, CourseDetails> = {
    'C++': {
        title: 'Comprehensive C++',
        description: 'An in-depth course on C++, covering everything from basic syntax to advanced features like templates, STL, and modern C++ standards. Perfect for beginners and those looking to strengthen their C++ skills for competitive programming and software development.',
        icon: C_PLUS_PLUS_ICON,
        tags: {
            certification: true,
            rating: '4.8 (1,234 reviews)',
        },
        stats: {
            lessons: 48,
            hours: 30,
            problems: 120,
        },
        modules: [
            { id: 1, title: 'Module 1: C++ Basics', lessons: [
                { id: 1, title: 'Introduction', duration: '10 min', type: 'video' },
                { id: 2, title: 'Variables & Data Types', duration: '20 min', type: 'reading' },
            ]},
            { id: 2, title: 'Module 2: Control Flow', lessons: [
                { id: 3, title: 'If-Else Statements', duration: '15 min', type: 'video' },
                { id: 4, title: 'Loops', duration: '25 min', type: 'practice' },
            ]}
        ]
    },
    'Python': {
        title: 'Python for Problem Solving',
        description: 'Learn Python from scratch and apply it to solve a variety of programming challenges. This course focuses on Python\'s standard library, data structures, and best practices for writing clean, efficient code.',
        icon: PYTHON_ICON,
        tags: {
            certification: true,
            rating: '4.9 (2,500 reviews)',
        },
        stats: {
            lessons: 55,
            hours: 28,
            problems: 150,
        },
        modules: [
            { id: 1, title: 'Module 1: Python Fundamentals', lessons: [
                { id: 1, title: 'Hello, Python!', duration: '8 min', type: 'video' },
                { id: 2, title: 'Lists and Dictionaries', duration: '22 min', type: 'practice' },
            ]}
        ]
    },
    'Algorithms': {
        title: 'Data Structures & Algorithms',
        description: 'A comprehensive guide to common data structures and algorithms. This course is essential for passing technical interviews and improving your problem-solving abilities.',
        icon: ALGORITHMS_ICON,
        tags: {
            certification: true,
            rating: '4.9 (5,100 reviews)',
        },
        stats: {
            lessons: 60,
            hours: 40,
            problems: 250,
        },
        modules: [
            { id: 1, title: 'Module 1: Core Data Structures', lessons: [
                { id: 1, title: 'Arrays and Strings', duration: '30 min', type: 'video' },
                { id: 2, title: 'Linked Lists', duration: '45 min', type: 'practice' },
            ]}
        ]
    }
};

const GENERIC_BOILERPLATE = `#include <iostream>
#include <string>
#include <vector>
#include <cmath>
#include <algorithm>

// Use this space to implement your solution

int main() {
    // Your code to read input and test the solution goes here
    std::cout << "Experiment boilerplate. Implement your solution." << std::endl;
    return 0;
}
`;

export const CPP_CHALLENGES: Challenge[] = [
    {
        id: 1,
        title: 'Print "Hello, World!"',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '99.0%',
        description: 'Write a program that prints "Hello, World!" to the console.',
        isSolved: false,
        boilerplateCode: `#include <iostream>\n\nint main() {\n    // Your code here\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}\n`,
        objective: 'Your first task in any new programming language is to master the art of printing output. Write a C++ program that prints the exact string `Hello, World!` to the console.',
        inputFormat: 'There is no input for this problem.',
        outputFormat: 'Output a single line containing the string "Hello, World!".',
        constraints: 'N/A',
        sampleInput: '',
        sampleOutput: 'Hello, World!',
        testCases: [{ id: '1', input: '', expectedOutput: 'Hello, World!', isLocked: true }],
    },
    {
        id: 2,
        title: 'Sum and Difference of Two Numbers',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '95.0%',
        description: 'Write a program that takes two integers as input and prints their sum and difference.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Your task is to take two integers as input and calculate their sum and difference. This will test your ability to handle basic input and perform arithmetic operations.',
        inputFormat: 'A single line containing two space-separated integers, `a` and `b`.',
        outputFormat: 'Print two lines. The first line should contain the sum of `a` and `b`. The second line should contain the difference (`a - b`).',
        constraints: '`1 <= a, b <= 1000`',
        sampleInput: '5 3',
        sampleOutput: '8\n2',
        testCases: [{ id: '1', input: '5 3', expectedOutput: '8\n2', isLocked: true }],
    },
    {
        id: 3,
        title: 'Repeat a String',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '92.0%',
        description: 'Create a program that reads a string and an integer, then prints the string repeated.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given a string `S` and an integer `N`, your task is to print the string `S` repeated `N` times consecutively.',
        inputFormat: 'The first line contains an integer `N`.\nThe second line contains a string `S`.',
        outputFormat: 'Print the resulting string on a single line.',
        constraints: '`1 <= N <= 10`\n`1 <= length(S) <= 100`\n`S` contains only lowercase English letters.',
        sampleInput: '3\nabc',
        sampleOutput: 'abcabcabc',
        testCases: [{ id: '1', input: '3\nabc', expectedOutput: 'abcabcabc', isLocked: true }],
    },
    {
        id: 4,
        title: 'Variables of Different Data Types',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '98.0%',
        description: 'Write a program that declares variables of different data types and prints their values.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'This challenge is about understanding C++ data types. You are given an integer, a floating-point number, and a character. Your task is to read them as input and print each one on a new line.',
        inputFormat: 'A single line containing an integer, a float, and a character, each separated by a space.',
        outputFormat: 'Print the integer on the first line, the float on the second line (with 2 decimal places), and the character on the third line.',
        constraints: 'The values will be within the standard range for their respective data types.',
        sampleInput: '10 3.14 z',
        sampleOutput: '10\n3.14\nz',
        testCases: [{ id: '1', input: '10 3.14 z', expectedOutput: '10\n3.14\nz', isLocked: true }],
    },
    {
        id: 5,
        title: 'Celsius to Fahrenheit',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '91.0%',
        description: 'Write a program that converts a temperature from Celsius to Fahrenheit.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given a temperature in Celsius, your task is to convert it to Fahrenheit using the formula `F = (C * 9/5) + 32` and print the result.',
        inputFormat: 'A single line containing a floating-point number `C` representing the temperature in Celsius.',
        outputFormat: 'Print the equivalent temperature in Fahrenheit, rounded to two decimal places.',
        constraints: '`-100.0 <= C <= 100.0`',
        sampleInput: '25.0',
        sampleOutput: '77.00',
        testCases: [{ id: '1', input: '25.0', expectedOutput: '77.00', isLocked: true }],
    },
    {
        id: 6,
        title: 'Circle Area and Circumference',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '90.0%',
        description: 'Calculate the area and circumference of a circle given its radius.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given the radius of a circle, calculate and print its area and circumference. Use `3.14159` as the value for pi (π).',
        inputFormat: 'A single line containing a floating-point number `r` representing the radius.',
        outputFormat: 'Print two lines. The first line should contain the area (`π * r^2`). The second line should contain the circumference (`2 * π * r`). Both values should be rounded to two decimal places.',
        constraints: '`0.0 < r <= 1000.0`',
        sampleInput: '10.0',
        sampleOutput: '314.16\n62.83',
        testCases: [{ id: '1', input: '10.0', expectedOutput: '314.16\n62.83', isLocked: true }],
    },
    {
        id: 7,
        title: 'Basic Arithmetic Operations',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '94.0%',
        description: 'Perform basic arithmetic operations on two integers.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given two integers, `a` and `b`, perform addition, subtraction, multiplication, and integer division. Print the result of each operation on a new line.',
        inputFormat: 'A single line with two space-separated integers, `a` and `b`.',
        outputFormat: 'Print four lines:\n1. `a + b`\n2. `a - b`\n3. `a * b`\n4. `a / b` (integer division)',
        constraints: '`1 <= b <= a <= 1000`',
        sampleInput: '10 3',
        sampleOutput: '13\n7\n30\n3',
        testCases: [{ id: '1', input: '10 3', expectedOutput: '13\n7\n30\n3', isLocked: true }],
    },
    {
        id: 8,
        title: 'Factorial of a Number',
        difficulty: 'Medium',
        category: 'Functions',
        maxScore: 20,
        successRate: '85.0%',
        description: 'Calculate the factorial of a given non-negative integer.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'The factorial of a non-negative integer `n`, denoted by `n!`, is the product of all positive integers less than or equal to `n`. For example, `5! = 5 * 4 * 3 * 2 * 1 = 120`. By definition, `0! = 1`. Your task is to write a program that calculates the factorial of a given integer `N`.',
        inputFormat: 'A single line containing one integer, `N`.',
        outputFormat: 'Print a single integer representing the factorial of `N`.',
        constraints: '`0 <= N <= 12`',
        sampleInput: '5',
        sampleOutput: '120',
        testCases: [{ id: '1', input: '5', expectedOutput: '120', isLocked: true }],
    },
    {
        id: 9,
        title: 'Bitwise Operators',
        difficulty: 'Easy',
        category: 'C++ (Basic)',
        maxScore: 10,
        successRate: '88.0%',
        description: 'Perform bitwise AND, OR, and XOR on two integers.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given two integers, `a` and `b`, compute their bitwise AND (`a & b`), bitwise OR (`a | b`), and bitwise XOR (`a ^ b`).',
        inputFormat: 'A single line containing two space-separated integers, `a` and `b`.',
        outputFormat: 'Print three integers on separate lines: the result of the AND, OR, and XOR operations, respectively.',
        constraints: '`0 <= a, b <= 1023`',
        sampleInput: '10 6',
        sampleOutput: '2\n14\n12',
        testCases: [{ id: '1', input: '10 6', expectedOutput: '2\n14\n12', isLocked: true }],
    },
    {
        id: 10,
        title: 'Check Number Sign',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '97.0%',
        description: 'Check if a number is positive, negative, or zero.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given an integer, determine if it is positive, negative, or zero. This challenge tests your understanding of basic conditional statements (`if-else`).',
        inputFormat: 'A single line containing an integer `N`.',
        outputFormat: 'Print "Positive", "Negative", or "Zero" (without quotes) based on the value of `N`.',
        constraints: '`-10^9 <= N <= 10^9`',
        sampleInput: '-5',
        sampleOutput: 'Negative',
        testCases: [{ id: '1', input: '-5', expectedOutput: 'Negative', isLocked: true }, { id: '2', input: '0', expectedOutput: 'Zero', isLocked: true }, { id: '3', input: '100', expectedOutput: 'Positive', isLocked: true }],
    },
    {
        id: 11,
        title: 'Largest of Three Numbers',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '96.0%',
        description: 'Find the largest of three given integers.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given three integers, `a`, `b`, and `c`, your task is to find and print the largest one among them.',
        inputFormat: 'A single line containing three space-separated integers.',
        outputFormat: 'Print a single integer which is the largest of the three.',
        constraints: '`-10^9 <= a, b, c <= 10^9`',
        sampleInput: '10 50 20',
        sampleOutput: '50',
        testCases: [{ id: '1', input: '10 50 20', expectedOutput: '50', isLocked: true }],
    },
    {
        id: 12,
        title: 'Grading System',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '93.0%',
        description: 'Assign a grade based on a student\'s score.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'A school has the following grading system:\n- Score >= 90: Grade A\n- 80 <= Score < 90: Grade B\n- 70 <= Score < 80: Grade C\n- 60 <= Score < 70: Grade D\n- Score < 60: Grade F\nGiven a student\'s score, determine their grade.',
        inputFormat: 'A single line containing an integer `score`.',
        outputFormat: 'Print the corresponding character grade.',
        constraints: '`0 <= score <= 100`',
        sampleInput: '85',
        sampleOutput: 'B',
        testCases: [{ id: '1', input: '85', expectedOutput: 'B', isLocked: true }],
    },
    {
        id: 13,
        title: 'Print Numbers with For Loop',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '99.0%',
        description: 'Print numbers from 1 to N using a for loop.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given an integer `N`, your task is to print all integers from 1 to `N`, each on a new line. This is a fundamental exercise for practicing loops.',
        inputFormat: 'A single integer `N`.',
        outputFormat: 'Print `N` lines, with each line containing a number from 1 to `N` in increasing order.',
        constraints: '`1 <= N <= 100`',
        sampleInput: '5',
        sampleOutput: '1\n2\n3\n4\n5',
        testCases: [{ id: '1', input: '5', expectedOutput: '1\n2\n3\n4\n5', isLocked: true }],
    },
    {
        id: 14,
        title: 'Sum of Even Numbers',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '94.0%',
        description: 'Calculate the sum of all even numbers up to N.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given an integer `N`, find the sum of all even numbers from 1 to `N` (inclusive). For example, if `N` is 10, the even numbers are 2, 4, 6, 8, 10, and their sum is 30.',
        inputFormat: 'A single integer `N`.',
        outputFormat: 'Print a single integer representing the sum.',
        constraints: '`1 <= N <= 1000`',
        sampleInput: '10',
        sampleOutput: '30',
        testCases: [{ id: '1', input: '10', expectedOutput: '30', isLocked: true }],
    },
    {
        id: 15,
        title: 'Multiplication Table',
        difficulty: 'Easy',
        category: 'Control Flow',
        maxScore: 10,
        successRate: '92.0%',
        description: 'Print the multiplication table for a given number.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given an integer `N`, print its multiplication table from 1 to 10 in the format `N x i = result`.',
        inputFormat: 'A single integer `N`.',
        outputFormat: 'Print 10 lines, each showing the multiplication of `N` with numbers from 1 to 10.',
        constraints: '`1 <= N <= 100`',
        sampleInput: '5',
        sampleOutput: '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50',
        testCases: [{ id: '1', input: '5', expectedOutput: '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50', isLocked: true }],
    },
    {
        id: 16,
        title: 'Function: Calculate Square',
        difficulty: 'Easy',
        category: 'Functions',
        maxScore: 10,
        successRate: '98.0%',
        description: 'Use a function to calculate the square of a number.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'To practice modular programming, create a function that takes an integer as input and returns its square. Then, call this function from your `main` function to compute the square of a given number.',
        inputFormat: 'A single integer `N`.',
        outputFormat: 'Print the square of `N`.',
        constraints: '`-1000 <= N <= 1000`',
        sampleInput: '9',
        sampleOutput: '81',
        testCases: [{ id: '1', input: '9', expectedOutput: '81', isLocked: true }],
    },
    {
        id: 17,
        title: 'GCD with Recursion',
        difficulty: 'Medium',
        category: 'Functions',
        maxScore: 20,
        successRate: '87.0%',
        description: 'Find the greatest common divisor (GCD) of two integers using recursion.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'The greatest common divisor (GCD) of two integers is the largest positive integer that divides both numbers without leaving a remainder. Implement a recursive function to find the GCD of two numbers using the Euclidean algorithm.',
        inputFormat: 'A single line containing two space-separated integers, `a` and `b`.',
        outputFormat: 'Print a single integer representing the GCD of `a` and `b`.',
        constraints: '`1 <= a, b <= 10^9`',
        sampleInput: '48 18',
        sampleOutput: '6',
        testCases: [{ id: '1', input: '48 18', expectedOutput: '6', isLocked: true }],
    },
    {
        id: 18,
        title: 'Function Pointers for Arithmetic',
        difficulty: 'Medium',
        category: 'Pointers',
        maxScore: 20,
        successRate: '80.0%',
        description: 'Use function pointers to call different arithmetic functions.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'This challenge tests your understanding of function pointers. Create four functions: `add`, `subtract`, `multiply`, and `divide`. Then, based on a character input (`+`, `-`, `*`, `/`), use a function pointer to call the corresponding function on two given integers.',
        inputFormat: 'The first line contains two space-separated integers. The second line contains a single character operator.',
        outputFormat: 'Print the result of the operation.',
        constraints: 'The divisor will not be zero for `/` operation.',
        sampleInput: '10 5\n*',
        sampleOutput: '50',
        testCases: [{ id: '1', input: '10 5\n*', expectedOutput: '50', isLocked: true }],
    },
    {
        id: 19,
        title: 'Initialize and Print an Array',
        difficulty: 'Easy',
        category: 'Arrays',
        maxScore: 10,
        successRate: '99.0%',
        description: 'Read N integers into an array and print them.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'The first step to mastering arrays is to read data into them and print it back out. You will be given an integer `N`, followed by `N` integers. Store these integers in an array and then print them, each on a new line.',
        inputFormat: 'The first line contains an integer `N`. The second line contains `N` space-separated integers.',
        outputFormat: 'Print the `N` integers from the array, each on a new line.',
        constraints: '`1 <= N <= 100`',
        sampleInput: '5\n1 2 3 4 5',
        sampleOutput: '1\n2\n3\n4\n5',
        testCases: [{ id: '1', input: '5\n1 2 3 4 5', expectedOutput: '1\n2\n3\n4\n5', isLocked: true }],
    },
    {
        id: 20,
        title: 'Reverse an Array',
        difficulty: 'Easy',
        category: 'Arrays',
        maxScore: 10,
        successRate: '93.0%',
        description: 'Reverse the elements of a given array.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given an array of `N` integers, your task is to reverse it and print the reversed array.',
        inputFormat: 'The first line contains an integer `N`. The second line contains `N` space-separated integers.',
        outputFormat: 'Print the `N` integers of the reversed array, separated by spaces.',
        constraints: '`1 <= N <= 100`',
        sampleInput: '5\n1 2 3 4 5',
        sampleOutput: '5 4 3 2 1',
        testCases: [{ id: '1', input: '5\n1 2 3 4 5', expectedOutput: '5 4 3 2 1', isLocked: true }],
    },
    {
        id: 21,
        title: 'Matrix Multiplication',
        difficulty: 'Medium',
        category: 'Arrays',
        maxScore: 20,
        successRate: '82.0%',
        description: 'Multiply two 3x3 matrices.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Given two 3x3 matrices, `A` and `B`, compute their product `C = A * B`. This is a classic problem to practice nested loops and 2D array manipulation.',
        inputFormat: 'The first three lines contain matrix `A` (3 rows, 3 columns). The next three lines contain matrix `B`. Each line has 3 space-separated integers.',
        outputFormat: 'Print the resulting 3x3 matrix `C`, with each row on a new line and elements separated by spaces.',
        constraints: 'Matrix elements will be between `-100` and `100`.',
        sampleInput: '1 2 3\n4 5 6\n7 8 9\n9 8 7\n6 5 4\n3 2 1',
        sampleOutput: '30 24 18\n84 69 54\n138 114 90',
        testCases: [{ id: '1', input: '1 2 3\n4 5 6\n7 8 9\n9 8 7\n6 5 4\n3 2 1', expectedOutput: '30 24 18\n84 69 54\n138 114 90', isLocked: true }],
    },
    {
        id: 22,
        title: 'Pointer Basics',
        difficulty: 'Easy',
        category: 'Pointers',
        maxScore: 10,
        successRate: '95.0%',
        description: 'Demonstrate pointer declaration, initialization, and dereferencing.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'This exercise will help you understand the fundamentals of pointers. Given an integer, you need to declare a pointer to it, and then print the value of the integer, its memory address, and the value accessed through the pointer.',
        inputFormat: 'A single integer `N`.',
        outputFormat: 'Print three lines:\n1. The value of `N`.\n2. The memory address of `N` (output may vary).\n3. The value of `N` accessed via the pointer.',
        constraints: '`1 <= N <= 1000`',
        sampleInput: '42',
        sampleOutput: '42\n(some memory address)\n42',
        testCases: [{ id: '1', input: '42', expectedOutput: '42\n42', isLocked: true }], // Address is non-deterministic
    },
    {
        id: 23,
        title: 'Swap Values with Pointers',
        difficulty: 'Easy',
        category: 'Pointers',
        maxScore: 10,
        successRate: '94.0%',
        description: 'Use pointers to swap the values of two integers.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Write a function that takes two integer pointers as arguments and swaps the values stored at those memory locations. This technique, known as "pass-by-reference", is a core concept in C++.',
        inputFormat: 'A single line containing two space-separated integers, `a` and `b`.',
        outputFormat: 'Print the values of `a` and `b` after swapping, separated by a space.',
        constraints: '`-10^9 <= a, b <= 10^9`',
        sampleInput: '10 20',
        sampleOutput: '20 10',
        testCases: [{ id: '1', input: '10 20', expectedOutput: '20 10', isLocked: true }],
    },
    {
        id: 24,
        title: 'Dynamic Memory Allocation',
        difficulty: 'Medium',
        category: 'Pointers',
        maxScore: 20,
        successRate: '85.0%',
        description: 'Dynamically allocate memory for an array, populate it, and print it.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Practice dynamic memory management. Read an integer `N`, dynamically allocate an array of `N` integers, read `N` values into it, print the values, and then free the allocated memory.',
        inputFormat: 'The first line contains `N`. The second line contains `N` space-separated integers.',
        outputFormat: 'Print the `N` integers from the dynamically allocated array, separated by spaces.',
        constraints: '`1 <= N <= 100`',
        sampleInput: '5\n10 20 30 40 50',
        sampleOutput: '10 20 30 40 50',
        testCases: [{ id: '1', input: '5\n10 20 30 40 50', expectedOutput: '10 20 30 40 50', isLocked: true }],
    },
    {
        id: 25,
        title: 'Simple Rectangle Class',
        difficulty: 'Easy',
        category: 'OOP',
        maxScore: 10,
        successRate: '96.0%',
        description: 'Create a simple Rectangle class with a method to calculate its area.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Your introduction to Object-Oriented Programming! Define a `Rectangle` class with integer attributes `width` and `height`. It should have a method `getArea()` that returns the area of the rectangle.',
        inputFormat: 'A single line with two space-separated integers representing width and height.',
        outputFormat: 'Print the area of the rectangle.',
        constraints: '`1 <= width, height <= 100`',
        sampleInput: '10 5',
        sampleOutput: '50',
        testCases: [{ id: '1', input: '10 5', expectedOutput: '50', isLocked: true }],
    },
    {
        id: 26,
        title: 'Class with Constructor',
        difficulty: 'Easy',
        category: 'OOP',
        maxScore: 10,
        successRate: '94.0%',
        description: 'Write a class with a constructor to initialize attributes.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Create a `Student` class with `name` (string) and `score` (int) attributes. Implement a constructor that takes the name and score as arguments to initialize the object. Also, create a `display()` method to print the student\'s details.',
        inputFormat: 'A single line with a string (name) and an integer (score), separated by a space.',
        outputFormat: 'Print in the format: `Name: [student_name], Score: [student_score]`',
        constraints: 'Name will not contain spaces.',
        sampleInput: 'Alice 95',
        sampleOutput: 'Name: Alice, Score: 95',
        testCases: [{ id: '1', input: 'Alice 95', expectedOutput: 'Name: Alice, Score: 95', isLocked: true }],
    },
    {
        id: 27,
        title: 'Operator Overloading',
        difficulty: 'Medium',
        category: 'OOP',
        maxScore: 20,
        successRate: '83.0%',
        description: 'Overload the addition operator for a custom class.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Create a `Complex` number class with `real` and `imag` (imaginary) parts. Overload the `+` operator so that you can add two `Complex` objects together just like regular numbers. `(a+bi) + (c+di) = (a+c) + (b+d)i`',
        inputFormat: 'Two lines, each containing two space-separated integers for the real and imaginary parts of a complex number.',
        outputFormat: 'Print the resulting complex number in the format `real+imagi` (e.g., `5+10i`).',
        constraints: 'Real and imaginary parts will be between `-100` and `100`.',
        sampleInput: '2 3\n4 5',
        sampleOutput: '6+8i',
        testCases: [{ id: '1', input: '2 3\n4 5', expectedOutput: '6+8i', isLocked: true }],
    },
    {
        id: 28,
        title: 'Basic Inheritance',
        difficulty: 'Medium',
        category: 'OOP',
        maxScore: 20,
        successRate: '88.0%',
        description: 'Demonstrate inheritance by creating a base and derived class.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Create a base class `Shape` with a string attribute `color`. Then, create a derived class `Rectangle` that inherits from `Shape` and has `width` and `height` attributes. The `Rectangle` class should be able to store its dimensions and its color.',
        inputFormat: 'A string for color, and two integers for width and height, each on a new line.',
        outputFormat: 'Print `Color: [color], Area: [area]`',
        constraints: '`1 <= width, height <= 100`',
        sampleInput: 'Blue\n10\n5',
        sampleOutput: 'Color: Blue, Area: 50',
        testCases: [{ id: '1', input: 'Blue\n10\n5', expectedOutput: 'Color: Blue, Area: 50', isLocked: true }],
    },
    {
        id: 29,
        title: 'Polymorphism with Virtual Functions',
        difficulty: 'Medium',
        category: 'OOP',
        maxScore: 20,
        successRate: '86.0%',
        description: 'Use virtual functions to achieve polymorphism.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Demonstrate runtime polymorphism. Create a base class `Animal` with a virtual method `speak()`. Create two derived classes, `Dog` and `Cat`, that override `speak()` to print "Woof" and "Meow" respectively. Your main function will use a base class pointer to call the correct method.',
        inputFormat: 'A single string, either "Dog" or "Cat".',
        outputFormat: 'Print "Woof" if the input is "Dog", and "Meow" if the input is "Cat".',
        constraints: 'Input will always be either "Dog" or "Cat".',
        sampleInput: 'Cat',
        sampleOutput: 'Meow',
        testCases: [{ id: '1', input: 'Cat', expectedOutput: 'Meow', isLocked: true }, { id: '2', input: 'Dog', expectedOutput: 'Woof', isLocked: true }],
    },
    {
        id: 30,
        title: 'Multiple Inheritance',
        difficulty: 'Medium',
        category: 'OOP',
        maxScore: 20,
        successRate: '81.0%',
        description: 'Create a program that demonstrates multiple inheritance.',
        isSolved: false,
        boilerplateCode: GENERIC_BOILERPLATE,
        objective: 'Showcase multiple inheritance. Create a `Person` class with a `name` and a `speak()` method. Create an `Employee` class with an `employeeId` and a `work()` method. Then, create a `Manager` class that inherits from both `Person` and `Employee` and can use methods from both base classes.',
        inputFormat: 'A string for the name and an integer for the employee ID, on separate lines.',
        outputFormat: 'Two lines of output, demonstrating calls to methods from both parent classes.',
        constraints: '`1 <= employeeId <= 10000`',
        sampleInput: 'John\n1234',
        sampleOutput: 'My name is John\nI am working with ID: 1234',
        testCases: [{ id: '1', input: 'John\n1234', expectedOutput: 'My name is John\nI am working with ID: 1234', isLocked: true }],
    },
];